FROM golang:1.23.2@sha256:adee809c2d0009a4199a11a1b2618990b244c6515149fe609e2788ddf164bd10 AS builder
RUN mkdir /build
WORKDIR /build
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download
COPY main.go main.go
COPY internal/ internal/
COPY pkg/ pkg/

ARG TARGETPLATFORM linux/amd64
ARG TARGETARCH

RUN echo "Current platform $TARGETPLATFORM arch $TARGETARCH"

# 示例命令，显示设置是否成功
RUN echo "Confirming environment variables: GOOS=${GOOS}, GOARCH=${GOARCH}"
RUN CGO_ENABLED=0 GOOS=linux GOARCH=$TARGETARCH go build -installsuffix 'static' -o spegel .

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /build/spegel /app/
WORKDIR /app
USER root:root
ENTRYPOINT ["./spegel"]
