image:
  repository: harbor.infini-ai.com/mizar/spegel-org/spegel
  pullPolicy: Always
  tag: "v0.2.0"

imagePullSecrets:
- name: mizar-robot

# -- Node selector for pod assignment.
nodeSelector:
  kubernetes.io/os: linux

serviceMonitor:
  enabled: true

spegel:
  # -- Minimum log level to output. Value should be DEBUG, INFO, WARN, or ERROR.
  logLevel: "INFO"
  # -- Registries for which mirror configuration will be created.
  registries:
    - https://cr.infini-ai.com
    - https://harbor.infini-ai.com  
  # -- Max ammount of mirrors to attempt.
  mirrorResolveRetries: 3
  # -- Max duration spent finding a mirror.
  mirrorResolveTimeout: "250ms"
  # -- Path to Containerd socket.
  containerdSock: "/run/k3s/containerd/containerd.sock"
  # -- Containerd namespace where images are stored.
  containerdNamespace: "k8s.io"
  # -- Path to Containerd mirror configuration.
  containerdRegistryConfigPath: "/var/lib/rancher/rke2/agent/etc/containerd/certs.d"
  # -- Path to Containerd content store..
  containerdContentPath: "/var/lib/rancher/rke2/agent/containerd/io.containerd.content.v1.content"

